# This workflow is triggered on a push to the main branch
name: Deploy to Firebase on Push
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install Function Dependencies
      - name: Install Function Dependencies
        run: npm --prefix functions install

      # 4. Install the Firebase Command Line Interface
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 5. Authenticate and Deploy to Firebase
      - name: Deploy to Firebase
        run: |
          # Write the service account key from the GitHub secret to a temporary file.
          # This is the correct way to handle authentication with a service account JSON.
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PLANAR_ALLIANCE_448817_H0 }}' > ./gcloud-sa-key.json

          # Set the GOOGLE_APPLICATION_CREDENTIALS environment variable to point to the key file.
          # The Firebase CLI will automatically use this for authentication.
          export GOOGLE_APPLICATION_CREDENTIALS=./gcloud-sa-key.json

          # Deploy to Firebase. The --force flag is added to allow deletion of old functions.
          firebase deploy --only hosting,functions --project planar-alliance-448817-h0 --non-interactive --debug --force
